---
driver:
  name: vagrant

provisioner:
  name: ansible_push
  sudo: true
  playbook: "test/integration/default.yml"
  ansible_config: "./ansible.cfg"
  verbose: "vvvv"
  diff: true
  mygroup: localhost
  groups: 
    localhost:
      - localhost
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: true
  ansible_verbosity: 2
  ansible_verbose: true
  enable_yum_epel: true
  extra_vars:
  # web2package_state: 'absent' 
   web2package_state: 'present' 

platforms:
  - name: ubuntu-16.04

suites:
  - name: default

# Fix for: https://github.com/neillturner/kitchen-ansible/issues/66
verifier:
  ruby_bindir: '/usr/bin'
